name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DIR_BUILD_RELEASE: build-release
  DIR_BUILD_DEBUG: build-debug
  BUILD_TYPE_DEBUG: Debug
  BUILD_TYPE_RELEASE: Release

jobs:
  build_debug:
    runs-on: ubuntu-latest
    container:
      image: kstmorozov/gateway_server:latest

    steps:
      - uses: actions/checkout@v2

      - name: conan-profile
        run: |
          conan profile new goodok-profile --detect --force
          conan profile update settings.compiler.version=10 goodok-profile
          conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.conan
          key: ${{ runner.os }}-cmake-debug-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: ${{ runner.os }}-cmake

      - name: conan-install
        run: |
          mkdir -p ${{github.workspace}}/${{env.DIR_BUILD_DEBUG}} && mkdir -p ${{github.workspace}}/${{env.DIR_BUILD_DEBUG}}/proto
          conan install -s build_type=${{env.BUILD_TYPE_DEBUG}} . --build=missing --profile goodok-profile -if ${{github.workspace}}/${{env.DIR_BUILD_DEBUG}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/${{env.DIR_BUILD_DEBUG}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_DEBUG}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-10

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/${{env.DIR_BUILD_DEBUG}} --config ${{env.BUILD_TYPE_DEBUG}}
  build_release:
    runs-on: ubuntu-latest
    container:
      image: kstmorozov/gateway_server:latest

    steps:
      - uses: actions/checkout@v2

      - name: conan-profile
        run: |
          conan profile new goodok-profile --detect --force
          conan profile update settings.compiler.version=10 goodok-profile
          conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.conan
          key: ${{ runner.os }}-cmake-release-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: ${{ runner.os }}-cmake

      - name: conan-install
        run: |
          mkdir -p ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}} && mkdir -p ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}}/proto
          conan install -s build_type=${{env.BUILD_TYPE_RELEASE}} . --build=missing --profile goodok-profile -if ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_RELEASE}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-10

      - name: Build
        run:  |
          cmake --build ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}} --config ${{env.BUILD_TYPE_RELEASE}}
          cmake --build ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}} --target package

      - name: Cache
        uses: actions/cache@v2.1.5
        with:
            path: ${{github.workspace}}/${{env.DIR_BUILD_RELEASE}}/*.deb
            key: ${{ runner.os }}-server-linux-deb-${{ hashFiles('${{github.workspace}}/${{env.DIR_BUILD_RELEASE}}/*.deb') }}
            restore-keys: ${{ runner.os }}-deb

#      - name: Test
#        run: |
#          ctest -C ${{env.BUILD_TYPE_RELEASE}}
#          # cmake --build ${{github.workspace}}/build --target test
#
#      - name: Update docker
#        run: cmake --build ${{github.workspace}}/build --target package